FROM node:18.17.0-slim as base

# Node.js app lives here
WORKDIR /app

# Throw-away build stage to reduce size of final image
FROM base as build

# Install packages needed to build node modules
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential node-gyp pkg-config python-is-python3

# Install node modules
COPY --link package-lock.json ./
RUN npm ci

# Final stage for app image
FROM base

# Copy built application
COPY --from=build /app /app

# Next.js collects anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# The following environment variable disables this feature
ENV NEXT_TELEMETRY_DISABLED 1
